# Coding Exercise Part 1: Tensor Operations with NumPy and PyTorch

### Objective:
Familiarize yourself with tensor operations using both NumPy and PyTorch.

### 1. Creating 2D tensors/arrays with random numbers


Using [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.array.html):

In [2]:
import numpy as np

# Create a 5x5 array with random numbers between 0 and 1
numpy_array = np.random.rand(5, 5)
print("NumPy Array:\n", numpy_array)

NumPy Array:
 [[0.4466631  0.21458155 0.07158866 0.7267139  0.54155705]
 [0.7106033  0.6125815  0.2744627  0.10870579 0.29506535]
 [0.75022029 0.99061484 0.26129498 0.39896143 0.74827092]
 [0.90481974 0.38617672 0.67879636 0.88651291 0.42355369]
 [0.6068795  0.0156771  0.98706262 0.84509481 0.63522379]]


Using [PyTorch](https://pytorch.org/docs/stable/tensors.html):

In [3]:
import torch

# Create a 5x5 tensor with random numbers between 0 and 1
pytorch_tensor = torch.rand(5, 5)
print("PyTorch Tensor:\n", pytorch_tensor)

PyTorch Tensor:
 tensor([[0.2401, 0.1527, 0.0022, 0.3366, 0.4202],
        [0.1553, 0.2129, 0.1247, 0.2903, 0.4715],
        [0.1446, 0.6974, 0.5764, 0.2948, 0.0653],
        [0.5875, 0.9470, 0.9328, 0.1660, 0.6329],
        [0.8671, 0.0323, 0.8167, 0.7655, 0.2161]])


### 2. Performing Tensor Operations


a. Compute Mean and Standard Deviation

In [4]:
# NumPy
numpy_mean = np.mean(numpy_array)
numpy_std  = np.std(numpy_array)
print(f"NumPy Array - Mean: {numpy_mean}, Standard Deviation: {numpy_std}")

# PyTorch
pytorch_mean = pytorch_tensor.mean().item()
pytorch_std  = pytorch_tensor.std().item()
print(f"PyTorch Tensor - Mean: {pytorch_mean}, Standard Deviation: {pytorch_std}")

NumPy Array - Mean: 0.5408673032707395, Standard Deviation: 0.28277197577736696
PyTorch Tensor - Mean: 0.40596234798431396, Standard Deviation: 0.300406277179718


b. Element-wise Multiplication

In [5]:
# Create another 5x5 tensor/array with random numbers between 1 and 2
numpy_array_2    = np.random.rand(5, 5) + 1
pytorch_tensor_2 = torch.rand(5, 5) + 1

# Element-wise multiplication
numpy_product   = numpy_array * numpy_array_2
pytorch_product = pytorch_tensor * pytorch_tensor_2

print("Element-wise Multiplication - NumPy:\n", numpy_product)
print("Element-wise Multiplication - PyTorch:\n", pytorch_product)

Element-wise Multiplication - NumPy:
 [[0.52134248 0.38077427 0.13436228 0.89613529 0.66297725]
 [1.3155759  0.84739285 0.50112151 0.14312373 0.48208978]
 [1.17098489 1.53275395 0.29759554 0.40280457 1.01629187]
 [1.78069681 0.57859823 1.11419182 1.0536357  0.476303  ]
 [1.12146236 0.03097094 1.64534836 1.08113631 0.90597663]]
Element-wise Multiplication - PyTorch:
 tensor([[0.3031, 0.2737, 0.0031, 0.4583, 0.8288],
        [0.2757, 0.4186, 0.2281, 0.5175, 0.7618],
        [0.2743, 1.2666, 0.7642, 0.3756, 0.1129],
        [0.6110, 1.0309, 1.1299, 0.2090, 1.0595],
        [1.1099, 0.0380, 0.9694, 1.4973, 0.3481]])


c. [Matrix Multiplication](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) with its Transpose

In [6]:
# Matrix multiplication
numpy_matmul   = np.dot(numpy_array, numpy_array_2)
pytorch_matmul = torch.mm(pytorch_tensor, pytorch_tensor_2)

print("Matrix Multiplication with Transpose - NumPy:\n", numpy_matmul)
print("Matrix Multiplication with Transpose - PyTorch:\n", pytorch_matmul)

Matrix Multiplication with Transpose - NumPy:
 [[3.46128186 3.3588942  3.40722322 2.46212486 2.58423522]
 [3.15110184 3.27881385 3.43504805 2.46658765 2.7866326 ]
 [5.28537457 5.18189301 5.41651724 3.92463381 4.40767437]
 [5.35791158 5.35507993 5.33758538 3.90503612 4.26157417]
 [5.11502888 5.1469512  4.73786686 3.58263131 3.96549431]]
Matrix Multiplication with Transpose - PyTorch:
 tensor([[1.4664, 1.5953, 1.5230, 1.8477, 1.9644],
        [1.7161, 1.7940, 1.6822, 2.0376, 2.1111],
        [2.9046, 3.0753, 2.6759, 2.6733, 3.0064],
        [5.1755, 5.5345, 4.7391, 5.1232, 5.5975],
        [3.7744, 4.1886, 3.5327, 3.6655, 4.8030]])


d. Sum of All Elements

In [7]:
# Sum of all elements
numpy_sum   = numpy_array + numpy_array_2
pytorch_sum = pytorch_tensor + pytorch_tensor_2

print(f"Sum of all elements - NumPy: {numpy_sum}")
print(f"Sum of all elements - PyTorch: {pytorch_sum}")

Sum of all elements - NumPy: [[1.61385708 1.98907834 1.94845397 1.95984744 1.7657628 ]
 [2.56195397 1.99589597 2.1002901  1.42532124 1.92890603]
 [2.31107503 2.53789022 1.40022056 1.40859429 2.10645796]
 [2.87283251 1.88444991 2.32021917 2.07502995 1.54809352]
 [2.45479553 1.99123051 2.65397648 2.12440252 2.061456  ]]
Sum of all elements - PyTorch: tensor([[1.5024, 1.9451, 1.3942, 1.6981, 2.3927],
        [1.9308, 2.1795, 1.9541, 2.0727, 2.0872],
        [2.0419, 2.5136, 1.9021, 1.5689, 1.7928],
        [1.6276, 2.0356, 2.1441, 1.4252, 2.3069],
        [2.1471, 1.2084, 2.0036, 2.7215, 1.8268]])


### 3. Conversion between PyTorch and NumPy

In [8]:
# Convert PyTorch tensor to NumPy array
converted_to_numpy = pytorch_tensor.numpy()
print("Converted PyTorch Tensor to NumPy:\n", converted_to_numpy)

# Convert NumPy array to PyTorch tensor
converted_to_pytorch = torch.from_numpy(numpy_array)
print("Converted NumPy Array to PyTorch Tensor:\n", converted_to_pytorch)

Converted PyTorch Tensor to NumPy:
 [[0.24012446 0.15271187 0.00220793 0.33661032 0.42017406]
 [0.15529287 0.21285236 0.12470305 0.29033828 0.47151047]
 [0.14458877 0.6974337  0.5763855  0.2948122  0.06532812]
 [0.587477   0.9469959  0.93276894 0.16601235 0.63292384]
 [0.86714154 0.03231543 0.81672186 0.7654837  0.21614325]]
Converted NumPy Array to PyTorch Tensor:
 tensor([[0.4467, 0.2146, 0.0716, 0.7267, 0.5416],
        [0.7106, 0.6126, 0.2745, 0.1087, 0.2951],
        [0.7502, 0.9906, 0.2613, 0.3990, 0.7483],
        [0.9048, 0.3862, 0.6788, 0.8865, 0.4236],
        [0.6069, 0.0157, 0.9871, 0.8451, 0.6352]], dtype=torch.float64)


### 4. Reshaping and Slicing Tensors


a. Create a tensor of shape (10, 2) filled with random numbers.
Reshape it to (5, 4) and (2, 10).

Using [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html):

In [11]:
# Reshaping
numpy_tensor = np.random.rand(10, 2)
print("Original NumPy Tensor:\n", numpy_tensor)

reshaped_5_4 = numpy_tensor.reshape(5, 4)
print("\nReshaped to (5, 4):\n", reshaped_5_4)

reshaped_2_10 = numpy_tensor.reshape(2, 10)
print("\nReshaped to (2, 10):\n", reshaped_2_10)

Original NumPy Tensor:
 [[0.5990149  0.02065641]
 [0.05746855 0.96515939]
 [0.41105287 0.95534216]
 [0.27066716 0.5730307 ]
 [0.87588652 0.23250385]
 [0.80727364 0.01953224]
 [0.04564169 0.86544295]
 [0.22513414 0.63572217]
 [0.35842781 0.70647822]
 [0.92249371 0.72489811]]

Reshaped to (5, 4):
 [[0.5990149  0.02065641 0.05746855 0.96515939]
 [0.41105287 0.95534216 0.27066716 0.5730307 ]
 [0.87588652 0.23250385 0.80727364 0.01953224]
 [0.04564169 0.86544295 0.22513414 0.63572217]
 [0.35842781 0.70647822 0.92249371 0.72489811]]

Reshaped to (2, 10):
 [[0.5990149  0.02065641 0.05746855 0.96515939 0.41105287 0.95534216
  0.27066716 0.5730307  0.87588652 0.23250385]
 [0.80727364 0.01953224 0.04564169 0.86544295 0.22513414 0.63572217
  0.35842781 0.70647822 0.92249371 0.72489811]]


Using [PyTorch](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html):

In [12]:
# Reshaping
pytorch_tensor = torch.rand(10, 2)
print("Original PyTorch Tensor:\n", pytorch_tensor)

reshaped_5_4 = pytorch_tensor.view(5, 4)
print("\nReshaped to (5, 4):\n", reshaped_5_4)

reshaped_2_10 = pytorch_tensor.view(2, 10)
print("\nReshaped to (2, 10):\n", reshaped_2_10)

Original PyTorch Tensor:
 tensor([[0.6204, 0.2132],
        [0.9560, 0.0201],
        [0.4692, 0.9232],
        [0.1912, 0.7744],
        [0.7445, 0.7390],
        [0.6327, 0.9745],
        [0.6382, 0.4700],
        [0.1661, 0.3009],
        [0.1651, 0.1832],
        [0.3964, 0.2347]])

Reshaped to (5, 4):
 tensor([[0.6204, 0.2132, 0.9560, 0.0201],
        [0.4692, 0.9232, 0.1912, 0.7744],
        [0.7445, 0.7390, 0.6327, 0.9745],
        [0.6382, 0.4700, 0.1661, 0.3009],
        [0.1651, 0.1832, 0.3964, 0.2347]])

Reshaped to (2, 10):
 tensor([[0.6204, 0.2132, 0.9560, 0.0201, 0.4692, 0.9232, 0.1912, 0.7744, 0.7445,
         0.7390],
        [0.6327, 0.9745, 0.6382, 0.4700, 0.1661, 0.3009, 0.1651, 0.1832, 0.3964,
         0.2347]])


b. From the original tensor, extract the first 5 rows. Extract the second column.

Using NumPy:

In [15]:
# Slicing
first_5_rows = numpy_tensor[:5, :]
print("\nFirst 5 rows:\n", first_5_rows)

second_column = numpy_tensor[:, 1]
print("\nSecond column:\n", second_column)


First 5 rows:
 [[0.5990149  0.02065641]
 [0.05746855 0.96515939]
 [0.41105287 0.95534216]
 [0.27066716 0.5730307 ]
 [0.87588652 0.23250385]]

Second column:
 [0.02065641 0.96515939 0.95534216 0.5730307  0.23250385 0.01953224
 0.86544295 0.63572217 0.70647822 0.72489811]


Using PyTorch:

In [18]:
# Slicing
first_5_rows = pytorch_tensor[:5, :]
print("\nFirst 5 rows:\n", first_5_rows)

second_column = pytorch_tensor[:, 1]
print("\nSecond column:\n", second_column)


First 5 rows:
 tensor([[0.6204, 0.2132],
        [0.9560, 0.0201],
        [0.4692, 0.9232],
        [0.1912, 0.7744],
        [0.7445, 0.7390]])

Second column:
 tensor([0.2132, 0.0201, 0.9232, 0.7744, 0.7390, 0.9745, 0.4700, 0.3009, 0.1832,
        0.2347])


### 5. Broadcasting and Reduction Operations

a. Broadcasting. Create a tensor A of shape (5, 1) and another tensor B of shape (1, 5). Perform element-wise addition between A and B.

Using NumPy:

In [19]:
# Broadcasting
A = np.random.rand(5, 1)
B = np.random.rand(1, 5)
broadcasted_sum = A + B
print("Broadcasted Sum:\n", broadcasted_sum)

Broadcasted Sum:
 [[1.07378261 0.69110379 0.99266905 1.03435406 1.33353102]
 [0.55215698 0.16947817 0.47104343 0.51272844 0.81190539]
 [1.01116757 0.62848876 0.93005402 0.97173903 1.27091598]
 [1.33770605 0.95502724 1.2565925  1.29827751 1.59745446]
 [0.69915558 0.31647676 0.61804202 0.65972704 0.95890399]]


Using PyTorch:

In [20]:
# Broadcasting
A = torch.rand(5, 1)
B = torch.rand(1, 5)
broadcasted_sum = A + B
print("Broadcasted Sum:\n", broadcasted_sum)

Broadcasted Sum:
 tensor([[0.2509, 0.5113, 0.9740, 0.2634, 0.3368],
        [0.7782, 1.0385, 1.5013, 0.7907, 0.8641],
        [0.8416, 1.1019, 1.5647, 0.8540, 0.9274],
        [0.9861, 1.2465, 1.7092, 0.9986, 1.0720],
        [0.5744, 0.8348, 1.2975, 0.5869, 0.6603]])


b. Reduction Operations. Compute the sum, mean, and max of a tensor along a specific dimension.

Using NumPy:

In [21]:
# Reduction Operations
tensor          = np.random.rand(5, 5)
sum_along_dim0  = np.sum(tensor, axis=0)
mean_along_dim1 = np.mean(tensor, axis=1)
max_value       = np.max(tensor)

print("\nSum along dimension 0:\n", sum_along_dim0)
print("\nMean along dimension 1:\n", mean_along_dim1)
print("\nMax value in the tensor:", max_value)


Sum along dimension 0:
 [3.01994437 3.39438573 2.88769912 2.86747861 2.72489477]

Mean along dimension 1:
 [0.46836046 0.8290167  0.53972162 0.65612133 0.48566041]

Max value in the tensor: 0.9614882047474075


Using PyTorch:

In [22]:
# Reduction Operations
tensor          = torch.rand(5, 5)
sum_along_dim0  = torch.sum(tensor, dim=0)
mean_along_dim1 = torch.mean(tensor, dim=1)
max_value       = torch.max(tensor)

print("\nSum along dimension 0:\n", sum_along_dim0)
print("\nMean along dimension 1:\n", mean_along_dim1)
print("\nMax value in the tensor:", max_value)


Sum along dimension 0:
 tensor([1.6873, 2.7115, 3.3427, 1.5592, 3.0849])

Mean along dimension 1:
 tensor([0.5304, 0.6338, 0.5354, 0.4992, 0.2784])

Max value in the tensor: tensor(0.9256)


### 6. Tensor Concatenation and Stacking

a. Create three tensors of shape (3, 3) filled with random numbers. [Concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) them along the first dimension. [Stack](https://numpy.org/doc/stable/reference/generated/numpy.stack.html) them along a new dimension.


Using NumPy:

In [23]:
tensor1 = np.random.rand(3, 3)
tensor2 = np.random.rand(3, 3)
tensor3 = np.random.rand(3, 3)

# Concatenation
concatenated = np.concatenate((tensor1, tensor2, tensor3), axis=0)
print("Concatenated Tensors:\n", concatenated)

# Stacking
stacked = np.stack((tensor1, tensor2, tensor3), axis=2)
print("\nStacked Tensors:\n", stacked)

Concatenated Tensors:
 [[0.70224898 0.90632779 0.76978965]
 [0.7265095  0.71790383 0.07782161]
 [0.19109754 0.96900444 0.85019917]
 [0.19929108 0.51961808 0.60969108]
 [0.66769539 0.14507379 0.45022004]
 [0.27141198 0.22386212 0.62270215]
 [0.77516034 0.94567004 0.26269446]
 [0.05316814 0.39754405 0.99942927]
 [0.67171768 0.22569191 0.76448642]]

Stacked Tensors:
 [[[0.70224898 0.19929108 0.77516034]
  [0.90632779 0.51961808 0.94567004]
  [0.76978965 0.60969108 0.26269446]]

 [[0.7265095  0.66769539 0.05316814]
  [0.71790383 0.14507379 0.39754405]
  [0.07782161 0.45022004 0.99942927]]

 [[0.19109754 0.27141198 0.67171768]
  [0.96900444 0.22386212 0.22569191]
  [0.85019917 0.62270215 0.76448642]]]


Using PyTorch:

In [24]:
tensor1 = torch.rand(3, 3)
tensor2 = torch.rand(3, 3)
tensor3 = torch.rand(3, 3)

# Concatenation
concatenated = torch.cat((tensor1, tensor2, tensor3), dim=0)
print("Concatenated Tensors:\n", concatenated)

# Stacking
stacked = torch.stack((tensor1, tensor2, tensor3), dim=2)
print("\nStacked Tensors:\n", stacked)

Concatenated Tensors:
 tensor([[0.1056, 0.5660, 0.0933],
        [0.4575, 0.7437, 0.7362],
        [0.5468, 0.4150, 0.0969],
        [0.0526, 0.5789, 0.8652],
        [0.4909, 0.0866, 0.1194],
        [0.0819, 0.8801, 0.5635],
        [0.4132, 0.5279, 0.1596],
        [0.7536, 0.1976, 0.7938],
        [0.5710, 0.0990, 0.8544]])

Stacked Tensors:
 tensor([[[0.1056, 0.0526, 0.4132],
         [0.5660, 0.5789, 0.5279],
         [0.0933, 0.8652, 0.1596]],

        [[0.4575, 0.4909, 0.7536],
         [0.7437, 0.0866, 0.1976],
         [0.7362, 0.1194, 0.7938]],

        [[0.5468, 0.0819, 0.5710],
         [0.4150, 0.8801, 0.0990],
         [0.0969, 0.5635, 0.8544]]])
